/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cms_categories: CmsCategory;
    cms_products: CmsProduct;
    orders: Order;
    refunds: Refund;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cms_categories: CmsCategoriesSelect<false> | CmsCategoriesSelect<true>;
    cms_products: CmsProductsSelect<false> | CmsProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_categories".
 */
export interface CmsCategory {
  id: number;
  name: string;
  slug: string;
  /**
   * Optional category description
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage your product catalog with e-commerce features
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_products".
 */
export interface CmsProduct {
  id: number;
  name: string;
  /**
   * Auto-generated from product name
   */
  slug: string;
  description?: string | null;
  /**
   * Price in ELURC tokens (stored in lamports)
   */
  price_elurc: number;
  /**
   * Price in euros (stored in cents)
   */
  price_eur: number;
  category: number | CmsCategory;
  stock: number;
  /**
   * Alert when stock falls below this number
   */
  low_stock_threshold?: number | null;
  /**
   * Automatically updated based on stock quantity
   */
  in_stock?: boolean | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage customer orders with e-commerce workflow
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'paid' | 'overpaid' | 'underpaid' | 'processing' | 'fulfilled' | 'cancelled' | 'timeout';
  /**
   * Total amount in ELURC tokens (lamports)
   */
  amountElurc: number;
  /**
   * Total amount in euros (cents)
   */
  amountEur: number;
  /**
   * Solana wallet public key
   */
  customerWallet: string;
  /**
   * Email address for order confirmation
   */
  customerEmail: string;
  shippingAddress: {
    fullName: string;
    streetAddress: string;
    city: string;
    postalCode: string;
    phoneNumber: string;
  };
  items: {
    product: number | CmsProduct;
    quantity: number;
    priceSnapshot: {
      elurc: number;
      eur: number;
    };
    id?: string | null;
  }[];
  /**
   * Solana transaction signature
   */
  transactionSignature?: string | null;
  /**
   * Timestamp when payment was confirmed
   */
  paidAt?: string | null;
  /**
   * Details about payment amount discrepancies
   */
  paymentDiscrepancy?: {
    hasDiscrepancy?: boolean | null;
    type?: ('none' | 'overpayment' | 'underpayment') | null;
    /**
     * Amount difference in ELURC (positive for overpayment, negative for underpayment)
     */
    differenceAmount?: number | null;
    /**
     * Timestamp when discrepancy was detected
     */
    detectedAt?: string | null;
    resolution?: ('pending' | 'refund_initiated' | 'refund_completed' | 'manually_approved' | 'cancelled') | null;
    /**
     * Admin notes about how the discrepancy was resolved
     */
    resolutionNotes?: string | null;
  };
  /**
   * Details about refund processing
   */
  refundInfo?: {
    refundAmount?: number | null;
    /**
     * Wallet address to send refund to
     */
    refundWallet?: string | null;
    /**
     * Solana transaction signature for refund
     */
    refundTransactionSignature?: string | null;
    refundInitiatedAt?: string | null;
    refundCompletedAt?: string | null;
    refundReason?: string | null;
  };
  /**
   * Timestamp when order was marked as fulfilled
   */
  fulfilledAt?: string | null;
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  /**
   * Timeline of all status changes
   */
  statusHistory?:
    | {
        status: string;
        timestamp: string;
        changedBy?: ('system' | 'admin') | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes for order management
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  refundNumber: string;
  /**
   * The order this refund is associated with
   */
  order: number | Order;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  /**
   * Amount to refund in ELURC tokens (lamports)
   */
  amount: number;
  /**
   * Solana wallet address to send refund to
   */
  walletAddress: string;
  /**
   * Reason for the refund
   */
  reason?: string | null;
  /**
   * Solana transaction signature for the refund
   */
  transactionSignature?: string | null;
  /**
   * Timestamp when refund was processed
   */
  processedAt?: string | null;
  /**
   * Timestamp when refund was completed
   */
  completedAt?: string | null;
  /**
   * Timestamp when refund failed
   */
  failedAt?: string | null;
  /**
   * Error message if refund failed
   */
  errorMessage?: string | null;
  /**
   * Admin user who processed the refund
   */
  processedBy?: (number | null) | User;
  /**
   * Internal notes about the refund
   */
  adminNotes?: string | null;
  /**
   * IP address of the admin who initiated the refund
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cms_categories';
        value: number | CmsCategory;
      } | null)
    | ({
        relationTo: 'cms_products';
        value: number | CmsProduct;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_categories_select".
 */
export interface CmsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_products_select".
 */
export interface CmsProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price_elurc?: T;
  price_eur?: T;
  category?: T;
  stock?: T;
  low_stock_threshold?: T;
  in_stock?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  amountElurc?: T;
  amountEur?: T;
  customerWallet?: T;
  customerEmail?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        streetAddress?: T;
        city?: T;
        postalCode?: T;
        phoneNumber?: T;
      };
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        priceSnapshot?:
          | T
          | {
              elurc?: T;
              eur?: T;
            };
        id?: T;
      };
  transactionSignature?: T;
  paidAt?: T;
  paymentDiscrepancy?:
    | T
    | {
        hasDiscrepancy?: T;
        type?: T;
        differenceAmount?: T;
        detectedAt?: T;
        resolution?: T;
        resolutionNotes?: T;
      };
  refundInfo?:
    | T
    | {
        refundAmount?: T;
        refundWallet?: T;
        refundTransactionSignature?: T;
        refundInitiatedAt?: T;
        refundCompletedAt?: T;
        refundReason?: T;
      };
  fulfilledAt?: T;
  trackingNumber?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        timestamp?: T;
        changedBy?: T;
        reason?: T;
        id?: T;
      };
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  refundNumber?: T;
  order?: T;
  status?: T;
  amount?: T;
  walletAddress?: T;
  reason?: T;
  transactionSignature?: T;
  processedAt?: T;
  completedAt?: T;
  failedAt?: T;
  errorMessage?: T;
  processedBy?: T;
  adminNotes?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}